name: Code Analysis

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "docs/**"

jobs:
  run_checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"
      - name: Run style checks
        run: ./gradlew checkstyleMain checkstyleTest
